### ISSUE TITLE
put("thing") + put("thing/edit") results in an error

### ISSUE THREAD

**Issue by Pomax** [nephics/noxmox#11]
interesting mox problem: calling a put("thing") will create a file "thing" in the temp dir that mox is using, and using a miniserver to serve that data shows it's there, and works great (after making the mini server serve everything as text/html content).

However, "thing" is not necessarily a file, just a URI that hides, for instance, "thing/index.html". 

Performing a put("thing/edit") makes mox throw a 403 AccessDenied error, because it doesn't know what to do: "thing/edit" look like it should be a dir "thing" with a file "edit" in it, but it can't make that dir because there's already a file called "thing". 

This might need a check to see if a put-path is being request for which one or more parts of the path are actually files, and do some kind of file-to-dir resolution, moving the file to .../index.html instead

**Comment by nephics** [comment]
S3 has no concept of subdirectories to buckets, but you are welcome to use slash in your object name, to get the impression of subdirectories.

**Comment by Pomax** [comment]
S3 doesn't, but the local file system certainly does, which is why this problem pops up. On S3 you can write a resource to `.../yourbucket/label`, and telling it you now also need something at `.../yourbucket/label/edit` is not a problem. Nox will handle this fine, but Mox won't, as it writes the `yourbucket/label` data as a file to the filesystem. When it is then told to put `yourbucket/label/edit`, it can't make that file because the function for ensuring the URI path is a sequence of existing directories fails on "label"; it exists, but is a file, so Mox can't make a dir with the same name.

Using slashes in the object name doesn't actually help us here, because unfortunately that's not supposed on windows, which will always resolve them as directory delimiters (often unknown fact: windows treats both `/` and `\` as valid path delimiters)

I'll see if I can make the `put` and `get` pair do a "is this dir a file? -> turn into dir/index.html instead" (which makes it do the same on S3 - putting "yourbucket/label" and then "yourbucket/label/index.html" means you will always get the index.html resource on either URI) with corresponding lookup when using `get`.

(of course that leaves the issue of a resource removal for `index.html` also removing the base resource, because they're the same thing on the filesystem, unlike on S3... the real way to solve this issue would be to not just store data on the filesystem, but to write a mapping for route to resource, with `put` writing the file to not-necessarily-where-asked, and `get` consulting the mapping table to see where to fetch the data from. That might, however, be a larger rewrite... =x)

**Comment by nephics** [comment]
Anything after the bucket-name is just a filename, and should be escaped if it contains characters that are not allowed (like slash). A simple URL escape might do the trick.

**Comment by Pomax** [comment]
fair enough, although for people who are used to `knox`, no such escaping is necessary to make S3 happy (might be nice to ensure nox/mox don't require escaping either? at least not manual escaping)

**Comment by Pomax** [comment]
sweet, thanks so much! I'm using a tiny server for serving mox content (currently primed to the "url" format that our webmaker.org tools push to s3) over at https://github.com/pomax/mox-server, would it be interesting to fold this into the mox side, so people can run `require("noxmox").mox.runServer(<port>)` for easy validation?

**Comment by nephics** [comment]
I would rather keep it simple and have the server component as a separate module. You already have working server code, so just publish it as module.
